<a href="https://colab.research.google.com/github/lmcanavals/algorithmic_complexity/blob/main/notebooks/af_divide_n_conquer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Divide and Conquer

In [7]:
import random
import numpy as np

## Find the largest element in a list

In [3]:
def getMax(a, i, j):
  if i == j:
    return a[i]

  med = (i + j) // 2
  maxi = getMax(a, i, med)
  maxd = getMax(a, med + 1, j)
  return maxi if maxi > maxd else maxd

In [4]:
arr = [random.randint(1, 100) for _ in range(20)]
print(arr)
maxim = getMax(arr, 0, len(arr)-1)
assert maxim == max(arr)
print(maxim)

[59, 1, 67, 71, 62, 12, 38, 99, 63, 88, 58, 77, 84, 99, 94, 1, 55, 72, 37, 100]
100


## Miltiply 2 numbers

In [5]:
def mult(a, b, n):
  if n == 1:
    return a * b

  ai = a // 10**(n//2)
  ad = a % 10**(n//2)
  bi = b // 10**(n//2)
  bd = b % 10**(n//2)
  z1 = mult(ai, bi, n//2) * 10**n
  z2 = (mult(ai, bd, n//2) + mult(ad, bi, n//2)) * 10**(n//2)
  z3 = mult(ad, bd, n//2)
  
  return z1 + z2 + z3

In [6]:
a = 548929495
b = 102043934
n = 16
res = mult(a, b, n)
assert res == a * b
print(res)

56014925158433330


## Matrix Multiplication

In [8]:
def matmul(a, b, c, i, ii, j, jj):
  if i == ii:
    temp = 0
    for k in range(len(a)):
      temp += a[i][k] * b[k][j]
    c[i][j] = temp
  else:
    imid = (i + ii) // 2
    jmid = (j + jj) // 2
    matmul(a, b, c,        i, imid,        j, jmid)
    matmul(a, b, c, imid + 1,   ii,        j, jmid)
    matmul(a, b, c,        i, imid, jmid + 1, jj)
    matmul(a, b, c, imid + 1,   ii, jmid + 1, jj)

In [10]:
a = np.random.randint(10, size=(8, 8))
b = np.random.randint(10, size=(8, 8))
print(a)
print(b)
c = np.zeros((8, 8))
matmul(a, b, c, 0, len(a) - 1, 0, len(a) - 1)
assert (c == np.matmul(a, b)).all()
print(c)

[[3 3 8 5 6 0 3 7]
 [3 2 1 1 4 1 3 9]
 [5 2 0 7 4 7 0 6]
 [6 8 1 2 2 7 9 6]
 [9 2 9 0 0 8 9 3]
 [2 1 7 2 5 5 0 5]
 [1 2 0 0 2 0 9 5]
 [0 4 7 4 3 2 0 3]]
[[7 5 6 2 3 7 2 4]
 [4 7 5 1 5 6 2 2]
 [3 3 3 8 8 8 9 8]
 [4 3 1 7 8 0 4 5]
 [5 9 8 5 4 9 3 8]
 [9 7 9 6 8 9 2 7]
 [1 3 3 3 9 1 6 0]
 [5 0 7 0 6 7 2 4]]
[[145. 138. 168. 147. 221. 209. 154. 183.]
 [113.  87. 145.  58. 140. 152.  73. 104.]
 [184. 145. 184. 123. 189. 188.  80. 164.]
 [197. 189. 229. 121. 263. 230. 131. 147.]
 [194. 169. 211. 167. 272. 249. 179. 180.]
 [142. 124. 160. 130. 173. 201. 112. 171.]
 [ 59.  64.  94.  41. 132.  81.  76.  44.]
 [101. 102. 108. 115. 154. 146. 106. 134.]]
