<a href="https://colab.research.google.com/github/lmcanavals/algorithmic_complexity/blob/main/notebooks/bo_floyd_warshall.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [19]:
def relax(cost, path, cost_uv, path_kj, u, v):
  if cost[u] + cost_uv < cost[v]:
    cost[v] = cost[u] + cost_uv
    path[v] = path_kj

def floydWarshall(G):
  n = len(G)
  cost = G.copy()
  path = np.full((n, n), -1)

  for (i, j), _ in np.ndenumerate(path):
    path[i, j] = i if G[i, j] != np.Inf else -1;

  for k in range(n):
    for i in range(n):
      for j in range(n):
        if i != j and i != k and k != j:
          relax(cost[i], path[i], cost[k, j], path[k, j], k, j)
  
  return cost, path

In [20]:
%%file 1.adjmatrix
0 5 0 0 0 0 0 0
0 0 1 4 0 0 0 0
0 9 0 0 6 0 5 0
0 8 0 0 0 8 0 0
0 0 0 0 0 0 7 1
0 9 0 2 0 0 5 0
0 0 0 0 4 0 0 0
0 0 0 0 0 5 6 0

Overwriting 1.adjmatrix


In [21]:
G = np.fromfile("1.adjmatrix", sep=" ").reshape((8, 8))
G[G == 0] = np.Inf
G

array([[inf,  5., inf, inf, inf, inf, inf, inf],
       [inf, inf,  1.,  4., inf, inf, inf, inf],
       [inf,  9., inf, inf,  6., inf,  5., inf],
       [inf,  8., inf, inf, inf,  8., inf, inf],
       [inf, inf, inf, inf, inf, inf,  7.,  1.],
       [inf,  9., inf,  2., inf, inf,  5., inf],
       [inf, inf, inf, inf,  4., inf, inf, inf],
       [inf, inf, inf, inf, inf,  5.,  6., inf]])

In [22]:
cost, path = floydWarshall(G)
print(cost)
print(path)

[[inf  5.  6.  9. 12. 17. 11. 13.]
 [inf inf  1.  4.  7. 12.  6.  8.]
 [inf  9. inf 13.  6. 12.  5.  7.]
 [inf  8.  9. inf 15.  8. 13. 16.]
 [inf 15. 16.  8. inf  6.  7.  1.]
 [inf  9. 10.  2.  9. inf  5. 10.]
 [inf 19. 20. 12.  4. 10. inf  5.]
 [inf 14. 15.  7. 10.  5.  6. inf]]
[[-1  0  1  1  2  3  2  4]
 [-1 -1  1  1  2  3  2  4]
 [-1  2 -1  1  2  7  2  4]
 [-1  3  1 -1  2  3  5  4]
 [-1  5  1  5 -1  7  4  4]
 [-1  5  1  5  6 -1  5  4]
 [-1  5  1  5  6  7 -1  4]
 [-1  5  1  5  6  7  7 -1]]
